name: ci-cd

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build up system
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements-dev.txt

      - name: Linting code
        run: |
          pip install flake8
          flake8 .

      - name: Test with pytest
        run: pytest
