name: ci-cd

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_testing
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - name: Build up system
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements-dev.txt

#      - name: Linting code
#        run: |
#          pip install flake8
#          flake8 .

      - name: Run migrations
        run: python manage.py migrate

      - name: Test with pytest
        run: pytest
